### ISSUE TITLE
Mobile Browser Bug. Modules and Images Overflow to the right of page

### ISSUE THREAD

**Issue by IkeTen** [pojome/elementor#1270]
On the latest and most versions of mobile browsers [android default browser, chrome, opera mini], Elementor has a quirk where the some images and modules distort to the right, overflowing the page. I have attached some screen shot images from the Elementor site below to visually show this issue. See how images shift to the right and overflow the page.
![16472816_1297133556996494_3748127654905974621_n](https://cloud.githubusercontent.com/assets/22121640/22586571/6d90ad50-e9f5-11e6-9a61-904233c3dd52.jpg)
![16473559_1297133610329822_5624886180640413800_n](https://cloud.githubusercontent.com/assets/22121640/22586574/714bf774-e9f5-11e6-916f-08c08b04afb4.jpg)
![16472816_1297133556996494_3748127654905974621_n](https://cloud.githubusercontent.com/assets/22121640/22586585/78d9bbb6-e9f5-11e6-8744-a196f3aa6f7d.jpg)

Thanks

**Comment by IkeTen** [comment]
@arielk please check out this bug report

**Comment by IkeTen** [comment]
@KingYes

**Comment by IkeTen** [comment]
@benpines

**Comment by arielk** [comment]
Does this problem also occurs on other sites?

I think the problem is not with Elementor only with our theme.

**Comment by IkeTen** [comment]
@arielk  It's with Elementor. It happens on GeneratePress and OceanWP. I have two other sites using other themes that have this bug.

**Comment by IkeTen** [comment]
Hi, seems this issue still persists.

**Comment by IkeTen** [comment]
This issue is persistent not only on opera mini but on most mobile browsers. Android default browser and chrome too

**Comment by IkeTen** [comment]
Narrowed it down to Opera mobile browser. Hmm

**Comment by kennie747** [comment]
Please I'm having the very same problem and need help. Opera displays my website's Elementor pages squeezed to the left while images overflow to the right of page.
Has this issue been resolved?  I can't seem to find any solutions.

**Comment by arielk** [comment]
I think it was fixed in recent versions, what version are you using?

**Comment by kennie747** [comment]
Thanks for responding Arielk. 
My Elementor version is 1.7.1.  
I believe that's the latest version.

**Comment by bainternet** [comment]
@kennie747 @IkeTen 

Please reopen if issue persists in latest version 1.8.5
