### ISSUE TITLE
[PRO] Required custom messages not working for form widget

### ISSUE THREAD

**Issue by jonatascabral** [pojome/elementor#1554]
## Description
I have a form widget on my contact page and I want to validate the data only on backend, without HTML5 validation, so I added a custom JS to add the attribute "novalidate" to the form to avoid this.
When I do the submit with required fields without value, the required custom message not work. I check the code and see the Ajax_Handler class try to get the "field_required" setting, but the field name of the required messages is "required_field_message".

## Steps to reproduce
Create new form widget;
In "Emails & Options" box check custom messages "yes";
Update "Required field Message";
Click "Save";
Inspect element and add novalidate attribute to the form, to avoid HTML5 validation;
Try submit, the required message will keep the default value "Required";

## Environment	
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.6.2
	MySQL version: 5.7.17
	PHP Version: 7.0.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	Elementor Library: Not connected (cURL error 28: Resolving timed out after 10521 milliseconds)

== WordPress Environment ==
	Version: 4.7.3
	Site URL: http://pj65.localhost:8080/wp
	Home URL: http://pj65.localhost:8080
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: pt-BR
	Timezone: America/Sao_Paulo
	Debug Mode: Active

== Theme ==
	Name: NHTV theme
	Version: 1.0.0
	Author: Challenge Creative
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt_BR
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

== Active Plugins ==
	ACF: Better Search
		Version: 1.0.0
		Author: Mateusz Gbiorczyk

	Advanced Custom Fields PRO
		Version: 5.5.11
		Author: Elliot Condon

	Easy Updates Manager
		Version: 6.3.0
		Author: Easy Updates Manager Team

	Elementor
		Version: 1.4.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.2.4
		Author: Elementor.com

	Mail Bank
		Version: 2.0.18
		Author: Tech Banker

	Radio Buttons for Taxonomies
		Version: 1.7.7
		Author: Kathy Darling

	WordPress Exporter
		Version: 0.0.3
		Author: zourbuth

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WordPress Post Type Archive Links
		Version: 1.3.1
		Author: Stephen Harris

	WPBruiser
		Version: 3.1.4
		Author: Mihai Chelaru

	Wp Export Categories & Taxonomies
		Version: 1.0.3
		Author: timersys

	WP Original Media Path
		Version: 1.6.1
		Author: RVOLA

== Debug ==
	Errors: There are no errors to display

**Comment by KingYes** [comment]
Fixed in EPro `1.3.0`. Thanks!

**Comment by KC20cy** [comment]
Hello,

I am using Elementor version 1.10.1 contact form integrated with Hubspot, the problem is still there.  Please advise.

Regards,

KC

**Comment by benjaminadrom** [comment]
Nearly 5 years later, the problem is still relevant in pro version

**Comment by benjaminadrom** [comment]
and STILL not fixed, 
do I get that "custom message" wrong? Does it even work?

**Comment by stxyist** [comment]
And Still in 2023... -_-

**Comment by staffguy** [comment]
same shit :) different day
