### ISSUE TITLE
Feature request: Make checkbox required

### ISSUE THREAD

**Issue by tscheipi** [pojome/elementor#1693]
Making a checkbox required for e.g. acception of terms of service.
If not set one can´t submit the form.

**Comment by parfilov** [comment]
Another wish is the link inside this "Terms" checkbox. There is the law in Russia and many other countries that people must to give consent to the processing of personal data. F****** bureaucracy but there's nothing to be done.
There would be three fields:
1. Before text;
2. Link (we could to add а link with ID for popup plugin trigger or separate page);
3. After text.
![terms](https://user-images.githubusercontent.com/12493645/33844174-b0b21de8-dec9-11e7-922e-a2594083a2d3.png)

**Comment by bainternet** [comment]
Done in v1.13.0

**Comment by ausdemnichts** [comment]
Hello @matipojo, the acceptance checkfield is a nice option but it doesn't solve all the problems we have with the checkboxes. There should be the option to select at least one check box. 
This is a basic function in forms and a must for a pro plugin. 

It would be nice if someone looks at it. #9706.

**Comment by benjaminadrom** [comment]
+99

**Comment by IlPizza79** [comment]
+1, that's really odd not having this feature by default :-(

**Comment by Gunstick** [comment]
What an obvious feature to not be there. Dissapointed.

**Comment by wordpressman** [comment]
Elementor team has to understand that when a client needs this feature, we are oblige to pay for another extension.... only because of this, because the rest is great ! Come on Elementor devs, bring us this feature ! ;-)

**Comment by al-migrateful** [comment]
I don't understand how this is Closed. Being able to make Checkbox fields required is absolutely a must in a Pro/Paid form tool. Makes me want to drop this and buy another plugin. Please add this to the roadmap!

**Comment by pepkolajk** [comment]
any solutions yet?

**Comment by salbatyku** [comment]
they do not fucking care about anything, just money and attracting more people. thousands of dev requests, nothing changes.

**Comment by Gunstick** [comment]
We just dumped elementor and did our theme the good old way. Server is also now about 10 times faster.

**Comment by Mit-Stern** [comment]
True, you can't make elementor pro form checkbox required field, BUT you can make the select box required ...
Use "select" instead and tell users that multiple selections are possible. And **Select multiple items: (PC) hold down the CTRL button. (Mac) Press and hold the Command key. ** 
And to know later (in email etc) what was selected (ad that to the select list in elementor): To differentiate between label and value, separate them with a pipe char ("|"). For example: First Name|f_name

**Comment by manig-metaweb** [comment]
Step : 1
elementor-pro\modules\forms\widgets\form.php

line 147 
	- function name " register_controls "
	- hide the "checkbox" 
Step : 2
elementor-pro\modules\forms\classes
line 150
	Replace the below function

	protected function make_radio_checkbox_field( $item, $item_index, $type ) {
		$options = preg_split( "/\\r\\n|\\r|\\n/", $item['field_options'] );
		$html = '';
		if ( $options ) {

			
			$element_required = ($item['required'] && 'checkbox' === $type)?"element_required":"";
			$item_id = $item['custom_id'];
			$html .= '<div class="elementor-field-subgroup ' . esc_attr( $item['css_classes'] ) . ' ' . $item['inline_list'] . ' '.$element_required . ' ' . $element_required.'-'.$item_id. '">';

			if($item['required'] && 'checkbox' === $type){
				$item_id = $item['custom_id'];
				$oninvalid = "this.setCustomValidity('Please check the any one of the checkbox if you want to proceed.')";
				$oninput = "setCustomValidity('')";
				// $html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '" oninvalid="' .$oninvalid .'" oninput="'. $oninput .'">';
				$html .='<input type="text" name="valid-'. $item_id .'" required="required" class="cs-validation-ck cs-validation-ck'. $item_id . '">';
				$html .= '<script type="text/javascript"> jQuery("document").ready(function(){
						jQuery(".'. $element_required .'-'. $item_id .' .checkbox").change(function(){
							if (jQuery(".'.$element_required.'-'. $item_id .' .checkbox:checked").length > 0){
								jQuery("input.cs-validation-ck'. $item_id . '").val("1");
    					//console.log("checked");
							}else{
    					// console.log("not checked");
								jQuery("input.cs-validation-ck'. $item_id . '").val("");

							}
				});});	</script>';
			}
			
			foreach ( $options as $key => $option ) {
				$element_id = $item['custom_id'] . $key;
				$html_id = $this->get_attribute_id( $item ) . '-' . $key;
				$option_label = $option;
				$option_value = $option;
				if ( false !== strpos( $option, '|' ) ) {
					list( $option_label, $option_value ) = explode( '|', $option );
				}

				$this->add_render_attribute(
					$element_id,
					[
						'type' => $type,
						'value' => $option_value,
						'id' => $html_id,
						'name' => $this->get_attribute_name( $item ) . ( ( 'checkbox' === $type && count( $options ) > 1 ) ? '[]' : '' ),
					]
				);

				if ( ! empty( $item['field_value'] ) && $option_value === $item['field_value'] ) {
					$this->add_render_attribute( $element_id, 'checked', 'checked' );
				}

				if ( $item['required'] && 'radio' === $type ) {
					$this->add_required_attribute( $element_id );
				}
				// elseif( $item['required'] && 'checkbox' === $type ){
				// 	$this->add_required_attribute( $element_id );

				// }

				$html .= '<span class="elementor-field-option"><input ' . $this->get_render_attribute_string( $element_id ) . ' class="checkbox"> <label for="' . $html_id . '">' . $option_label . '</label></span>';
			}
			$html .= '</div>';
		}

		return $html;
	}

Step : 3 Add the below CSS 

/* Form validation */
input.cs-validation-ck {
    opacity: 0;
    width: 0px !important;
    height: 0px !important;
    padding: 1px !important;
    margin: 0 !important;
    border: none !important;
}

**Comment by eric802222** [comment]
+99

**Comment by WebByCraig** [comment]
+1

**Comment by chetanharvara** [comment]
> input.cs-validation-ck {
> opacity: 0;
> width: 0px !important;
> height: 0px !important;
> padding: 1px !important;
> margin: 0 !important;
> border: none !important;
> }

Thank You Buddy

**Comment by zovatrop** [comment]
I don't understand how this is not implemented yet...

**Comment by jodiroseduncan** [comment]
+1 seriously elementor

**Comment by marowi85** [comment]
+1

Could someone from Elementor comment on this feature request? It has been requested for many years and would be a useful feature. Thanks.

@matipojo @rami-elementor

**Comment by Nuclarium** [comment]
actually still waiting^^

**Comment by ricohlmann** [comment]
5 Years later :D

**Comment by Jeremy-VVu** [comment]
+1 ....
We need it !

**Comment by steveindzine** [comment]
+1

**Comment by elementor-bugfinder** [comment]
wtf... +999 still 2024 and cant use it

**Comment by fatihturan** [comment]
Can't believe that we still lack this feature. The Elementor team surprised me with some minor issues like this.

**Comment by agenciaRSE** [comment]
yoooooo

**Comment by wikiwyrhead** [comment]
I can’t believe I’m here reading these comments after struggling so much just to validate my multiple checkboxes. Why hasn’t this feature been added yet? It’s so frustrating spending a whole week just trying to make a checkbox validation work.

**Comment by FahadTKh** [comment]
Looks like they're not going to implement it anytime soon.

**Comment by s1awek** [comment]
Wow, it's 2025 and Elementor pro still doesn't have the option to mark the checkbox as required. Is this a joke?

**Comment by jimthedj65** [comment]
the fact this still isn't fixed is an embarrassment.

**Comment by bodhi1970** [comment]
+1 when will this be available?

**Comment by Elliria** [comment]
I'm all for this. Related issues: [#45084](https://github.com/orgs/community/discussions/45084) and [#9706](https://github.com/elementor/elementor/issues/9706).

**Comment by therealgladius** [comment]
I made a plugin for that: https://github.com/therealgladius/required-checkboxes-for-elementor-forms
