### ISSUE TITLE
Elementor 1.5.0 - Beta Release (RC3 updated)

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#1827]
===========
## [RC3 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/1827#issuecomment-310905726)
===========

Hi Beta tester,

Elementor 1.5 is an important release and includes many exciting features. Please review it carefully.

**Let's review the changes we have introduced:**

### UI Editor

This version includes some major improvements in the editor itself.

- We introduced a separation between the section and column management, so users can select sections or columns much more easily.
- We added an 'Add Section' button to the section settings, so as to enable users to add a new section between existing sections. You no longer need to drag sections for that.
- We re-wrote and vastly improved the entire drag and drop functionality.
- We added the option to set a specific numeric column width inside the panel. We also added a visible column width scale that appears between columns when you resize them.

### Design

- Element Hover: We added another style setting for regular and hover states. With this setting, you can control the hover states for: background, background overlay, border, border radius, box shadow.
- Added responsive mode for Column Width control (Including Tablet! #418)
- Added an inset option for box-shadow.
- Added Control over the spacing between the widgets. You can define this globally on Elementor settings screen or  #specifically per column.
- Added the ability to control the delay of Entrance animation.

### Version Control

- You can now downgrade to a previous version of Elementor and Elementor Pro from the Elementor settings page `(Elementor > Tools > Versions)`.
- You can set Elementor to notify about beta plugin updates. Use this option if you would like to test new beta versions on your development environment.

### Other new features

- We added the ability to customize mobile editing for: Image, Image box, image carousel, divider and minimum section height.
- We improved the accessibility of our editing panel.
- Added the possibility to define every link as no-follow.
- Added tabs to the Elementor settings area in the dashboard.
- Added control over the HTML tag for section and columns, including `div, section, aside, header, footer, etc...`
- Added control over Z-Index for each element `(Advanced Tab > Element Style > Z-Index)`
- Compatibility with the new WordPress 4.8 widgets (Rich Text, Image, Video and Audio).

### Notes:
- In order to add compatibility to the new Z-Index option, we had to delete the value`z-index: 1;` from the class `.elementor-widget-wrap`. This may cause issues for past pages built with Elementor, if you've used negative margins in past. In order to deal with these issues, you can use the new Z-Index control.
- If you are using Elementor Pro, please update to the latest 1.5.2 version for maximum compatibility.
- Deprecated: Mobile Width control is no longer supported. Please use the Column Width control in the Layout tab instead.

### Instructions what exactly to do
- You are invited to download the new Beta RC3 here:
https://downloads.wordpress.org/plugin/elementor.1.5.0-RC3.zip 
- This is not a stable version and we advise to use it in your dev website. We would really appreciate if you could do as many tweaking and testing of the different options, to squeeze out any possible bugs.
- Designated time for release:  June <s>26</s> 28, 2017

**For bugs and remarks, please reply with a comment below!**

Many thanks for your support and help!

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers](https://my.elementor.com/beta/)

**Comment by WPDevHQ** [comment]
@arielk  Elementor Pro 1.5.1 not available yet? Or did you mean 1.5.0?

**Comment by copen8** [comment]
I might have found a possible bug in the new hover settings. 
I created a heading widget, and set a green background inside the widget then its normal mode. When I tried to add a gradient effect then you hover the widget.  The effect itself  works but there is something not right with the transition duration.
No matter what value I put in the transition duration it won't effect the transition as it supposed to.

Worth notice then I switched to a solid color instead of gradient in hover-mode, the transition duration worked just fine.

**Comment by arielk** [comment]
@WPDevHQ V1.5.1 has already been released in the last hour, please check it again.

**Comment by WPDevHQ** [comment]
Got it now, thanks

**Comment by copen8** [comment]
Possible issue with Z-index

I tried to use the z-index option. For me it works fine then I used positive values. But as soon as you set a negative z-index e.g -1 z-index the problem start.  

My config:
I created one section, with one column and a heading widget inside the column . I added negative z-index value which resultated in that I was not able to select section,nor column nor heading-widget. 

The only way to restore the page was to go via the google chrome inspection tool and from there put in positive z-index value because i could not select the elements through Elementor.

**Comment by copen8** [comment]
Issue with video background

Video background for my section don't work. It works when you are in edit mode. But on the live site nothing happens. It's just white.

**Comment by carasmo** [comment]
The .zip has many `Illegal string offset 'height' ` and `Illegal string offset 'width' ` where is the other zip? I can't find it.

**Comment by carasmo** [comment]
With the file https://downloads.wordpress.org/plugin/elementor.1.5.0-RC1.zip I get bunches of errors here: `wp-content/plugins/elementor/includes/controls/groups/image-size.php on line 105`

**Comment by pingram3541** [comment]
First how do we get notifications about beta releases?  I just happened to discover this topic coming here to find out why custom css is gone for every except page and sections.  We need an explanation quick please, I will not upgrade any of my sites for fear of breaking them.

**Comment by LearnWPBasics** [comment]
So far so good with what I have been able to test 👍 

And thank you SO much for manual column widths! :) 

However, I am not all fond of the new "hover" behavior for the widget's edit, duplicate, save and delete functionality. It increases the workflow. For example, say I wanted to duplicate a text widget. Previously, all I needed to do was hover in the text widget and the selections would appear where I could go directly to the duplicate icon. The way it is now, I have to first go to the edit icon and hover and THEN select the duplicate icon. Doesn't seem like much if one is doing it "here and there" but if one is doing all day, every day, I can feel the arthritis in my shoulder acting up! LOL :) Long story short: I prefer the current method.

I do really like the separation of the columns and sections though! The addition of the "Add" for sections is really going to make a positive difference .

While on the subject of these items, is there any specific reason they need to be that small? First thing I do on an Elementor install is add the CSS I came up with to increase the size and add some padding. I've already adjusted the CSS for 1.5 ;) My (and I am sure many others) eyes aren't what they were 30 years ago! LOL

All in all, a fantastic update! Keep up the awesome work 👍

**Comment by joshmarom** [comment]
Hi @pingram3541 .
In order to get notified about new beta releases, you may join our beta testers group here: https://my.elementor.com/beta/
Additionally, as mentioned by the op, from this version on,

> You can set Elementor to notify about beta plugin updates. Use this option if you would like to test new beta versions on your development environment.

Regarding your issue with Custom CSS, did this issue occur as a consequence of upgrading to 1.5, or is it unrelated?

**Comment by pingram3541** [comment]
Thx @joshmarom  and I know that I have done that because I was invited to a beta test before but I didn't get notified this time, only last time...at least I think it was last time, you see I can't say for sure really because I don't recall the version I did test for or how many there may have been since maybe I didn't get notified about them either, am I making sense =)

I signed up again just to be sure.

Also to make things even more interesting I realized after I posted here that the CSS issue was occurring w/ 1.51Pro and 1.48, not the beta version because I initially thought "this" thread was for the "pro" beta and we were now a version past that and I was wondering how I missed it but even now that I think about it, maybe that is what I signed up for previously...that is, if you have different beta programs for each.

*forehead slap*

**Comment by KingYes** [comment]
@carasmo Did you have any custom code on your site? Maybe one plugin add/remove the image sizes from WP? If you, please share with me..

**Comment by joshmarom** [comment]
@copen8 Regarding the transition on hover, you need to understand how CSS works and only expect what can be achieved with CSS.
A transition is only applicable between two values of the same property, for example: from one color to another, or from one opacity value to another, but not from one property to another property (background-color to background-image).
It's also worth mentioning that to date, it is not possible to have a transition between two gradients.

**Comment by cavalierlife** [comment]
Love the new features. I especially like the UI editor changes and the additional hover states available. The only issue I've seen so far is with the animation delay. I set an element to animate, then applied a delay (tried various amounts of time delay), and it first animates the element once, then waits the required amount of delay time, and then animates it again. I expected it to not animate at all until after the delay time set. Maybe my expectations of the feature are wrong.

**Comment by badcat** [comment]
In 1.5.0-RC1 - from the Elemetor > Settings sub menu, the other tabs (General, Advanced) are not selectable. Issue with the JS?  I have no other plugins active.  The same issue occurs with Elementor > Tools - Tabs are not selectable (Replace URL, Versions, Maint Mode)

**Comment by pingram3541** [comment]
@badcat I can confirm they are indeed working on my install.  Do you see any browser console errors?

**Comment by badcat** [comment]
@pingram3541 Interesting... they do work in Chrome 59, but not in Safari 10.1.1

**Comment by pingram3541** [comment]
@badcat, yep, confirmed same here.

**Comment by badcat** [comment]
@pingram3541 and that's why they call me "Pest Control"  :)

**Comment by badcat** [comment]
1.5.0 RC1 - Should pressing the Save Changes button from any of the sub tabs (Style, Adv etc) on Tools or Settings send the user back to the first "General" tab?

**Comment by crsmoore** [comment]
Not sure if this issue has been raised yet, but why does the "Add New Section +" button add a section ABOVE the current one. Wouldn't it make more sense to have it add a new Section BELOW the one you're working on, as you usually create a page from top to bottom?

**Comment by crsmoore** [comment]
I also agree with some of the comments above that some of the main screen editor controls are a little too small now. They are really hard to work with, select, and *see* in some cases, haha...

cc: @LearnWPBasics

**Comment by pingram3541** [comment]
I agree, that makes sense to me too but then again you already have a way to add a new section below.  I think that is what they were going for, when wanting to add a section above an existing one you now don't have to add one below and then drag it up, this handles that for you.

The way I initially interpreted the feature as described above was I thought it was just an easier way to add inner sections within an existing one right from it's hover menu but I was a tad off in that assessment =)

**Comment by crsmoore** [comment]
I personally think they should have a way to "Add Section Above" / "Add Section Below" and be done with it all in one shot. :)

**Comment by pingram3541** [comment]
@badcat "Should pressing the Save Changes button..." Yes, it's actually one page so technically you can make changes in all tabs and then save once.

**Comment by Micemade** [comment]
I can confirm a this error ( as **carasmo** ), too:
`Warning: Illegal string offset 'height' in ... \wp-content\plugins\elementor\includes\controls\groups\image-size.php on line 105`

**Comment by tscheipi** [comment]
"We introduced a separation between the section and column management, so users can select sections or columns much more easily" --> it´s very hard to meet: 
![meetthesection](https://user-images.githubusercontent.com/26705660/27127444-63d876ae-50fb-11e7-8b6f-2d0da8aceb39.gif)

**Comment by tscheipi** [comment]
"We added the option to set a specific numeric column width inside the panel" --> do you mean the column size in the layout? if yes: doesn´t work here; if not: where to find?

**Comment by tscheipi** [comment]
"We improved the accessibility of our editing panel" --> in which way? for me there´s nothing new

**Comment by tscheipi** [comment]
"Added the possibility to define every link as no-follow." --> is generating: nofollow=""; shouldn´t it be rel="nofollow" !?
Is there a way to implement that into the text editor as well?

**Comment by cornesnijders** [comment]
I noticed that the image carrousel shows arrows and dots now after the update (inside global widget with is inside a template used as header), while they where hidden before the upgrade.

**Comment by Ver3** [comment]
Only just now started testing, apologies, had now time until now. Testing is done on this test site: verdi.nu

1. As the instruction mentioned, I had to re-do negative margins. But then this happened:
![image](https://user-images.githubusercontent.com/20367733/27176987-25afeaae-51c5-11e7-86ba-3fad5084550d.png)
The form partly flips to te top left corner. After refresh it's gone, but returns randomly.

2. When editing column size you cannot revert to an empty field to get back to default. Onze you enter a value it MUST have a value. Making it empty results in value '10'.
![image](https://user-images.githubusercontent.com/20367733/27177105-88bd5a64-51c5-11e7-804d-500eb605a457.png)

3. On mobile some elements end up in different places, one is out of sight.

No reply needed, this is just feedback. If you wish to do some of your own testing on this domain, let me know., I'll give you admin access.

Loving some of the new features and UI, Cheers!

**Comment by webtikinfo** [comment]
Since I Installed the 1.5RC1 I can't load anymore some custom Elementor template I made ... or with some difficulties :) When It allow me to edit those template I had those lines in my Chrome console.
I'm using  wordpress 4.8 FR and elemento PRO 1.5.2 - Anywhere Elementor Pro 2.0 as well

More than that those template didn't appear as well from my pages like before  :(

`frontend.min.js?ver=1.0.4:358` Uncaught TypeError: Cannot read property 'querySelector' of null
    at cbpHorizontalSlideOutMenu._init (frontend.min.js?ver=1.0.4:358)
    at cbpHorizontalSlideOutMenu (frontend.min.js?ver=1.0.4:348)
    at frontend.min.js?ver=1.0.4:450
    at frontend.min.js?ver=1.0.4:452
    at frontend.min.js?ver=1.0.4:455

editor.min.js?ver=1.0.4:357 Uncaught TypeError: Cannot read property 'querySelector' of null
    at cbpHorizontalSlideOutMenu._init (editor.min.js?ver=1.0.4:357)
    at cbpHorizontalSlideOutMenu (editor.min.js?ver=1.0.4:348)
    at editor.min.js?ver=1.0.4:449
    at editor.min.js?ver=1.0.4:451
    at `editor.min.js?ver=1.0.4:454`

**Comment by Ver3** [comment]
Not sure if this helps, but here are some more thoughts and thing I feel that are missing.

- Cannot use responsive settings to hide a column on mobile.
- Responsive settings are always in tab "Advanced" but not in column settings (there it is in tab 'Layout'). Strange.
- When you hide something in mobile view, it is still shown (Although I can understand why from a UX point of view).
- (Box) shadow for icons still seem missing.
- Column size value seems a % but this is not indicated.
- After entering columns size value, there seems no way to center the column again.
- Copy-pasting transparant color value in box shadow field of Flip box, only pastes the value partly.

![image](https://user-images.githubusercontent.com/20367733/27178302-03f075d2-51ca-11e7-93e1-834fdebb65e9.png)

More to follow as I'm testing. No reply needed, just giving feedback.

**Comment by fuzzyness** [comment]
I'm having trouble accessing the column controls under certain conditions. They're unclickable.

I'm not sure what exact conditions cause the problem though.

I've recorded a very quick video here showing the issue:

https://cl.ly/2w2P2V180e2L

Happy to provide more info or try different things.

**Comment by Ver3** [comment]
Loving the new z-index control. Awesome!

- Wish Z-index could also be set on hover to create 'button going up on mouse over'-effect.
- REALLY missing a way to save a section as global (although I can imagine this is very difficult, Divi really botched that one up in terms of UI/UX.
- When border radius AND shadow is applied on Flip Box, you see white corners sticking out.
![image](https://user-images.githubusercontent.com/20367733/27178689-9466e5b4-51cb-11e7-84b0-6b5f4a46cf1c.png)
- Image height in Flip Box not responsive. On mobile it's way too small or on desktop way to big.
![image](https://user-images.githubusercontent.com/20367733/27178986-e574dfdc-51cc-11e7-97ba-559139784d72.png)

No reply needed, just feedback.

**Comment by fuzzyness** [comment]
More on my issue with columns settings not being clickable:

https://cl.ly/3L1A3B2u1m22

Odd that I can't click it in the 3 col section at the top, but _can_ in another 3 col section further down the page.

But the nested section column still remains unclickable. 

This site is a fresh install. No custom CSS and minimal plugins.

**Comment by crsmoore** [comment]
I'm not seeing the problems @fuzzyness has found above (with not being able to select the column settings). Short video: https://www.screencast.com/t/7IOHS76M

I also tried the nested columns, and didn't have trouble selecting the column settings either. All good here.

**Comment by arielk** [comment]
@fuzzyness Which browser are you using?

**Comment by fuzzyness** [comment]
@arielk Google Chrome (59.0.3071.104) on Mac (10.12.5).

If I add a widget to a column, I can then access that column's settings. @WPDevHQ mentioned today on Facebook he's had the same issue too, and suggested this workaround.

Another video here (no sound this time): https://cl.ly/3w432D303c1Z

Firstly I show how I can't access the column settings. Then I add a heading widget and then _can_ access the settings. But notice actually for columns 2 and 3 I still have trouble, it's hit-and-miss. I can only really activate the slideout panel in a small area of the column icon.

**Comment by fuzzyness** [comment]
Ok, I've just started again from scratch with a completely fresh install. Literally nothing but Twenty Seventeen and Elementor 1.5. And I can access all the column settings no problem!

I'm investigating what's happening! Back as soon as possible.

**Comment by fuzzyness** [comment]
Ok - I've got it. It's when the 'NavMenu Addon' plugin is installed. Activate it - I have the column setting issue. Deactivate it - the issue is fixed.

I made a mistake yesterday saying my issue was on a fresh install. It'd been a long day, way too many tabs open, etc. I'd overlooked that I had this plugin installed, I was just about to start recording a tutorial video about it.

Sorry for the inaccuracy re. my setup. I've informed @WPDevHQ.

**Comment by fuzzyness** [comment]
@WPDevHQ has just kindly pushed an update for his NavMenu Addon plugin which I'm happy to report 100% solves the non-clickable column setting issue. :)

**Comment by joshmarom** [comment]
@Ver3
We would like to take a closer look at the negative margins issue you mentioned.
Could you send me access details to this page to josh@pojo.me ? thx.

Regarding box shadow for flip box, You are right, the box shadow applies to the entire widget, only with custom CSS can it be applied to the front and back divs inside the widget.

Regarding responsive Image height in Flip Box, good call, we added that.

**Comment by joshmarom** [comment]
I just wanted to point out, in this thread, the main goal is to find out about issues that are **directly related to 1.5**!

Many of the issues reported here are not at all related. While we are very greatfull for any kind of feedback, even not related to the new beta version, in this particular thread, we would really appreciate it if you please try to keep it focused on 1.5 issues.

Thank you guys very much for your cooperation and contribution. Your feedback is what allows us to deliver a better, more stable product.

**Comment by fuzzyness** [comment]
I'm confused @joshmarom. Going back through the thread, it looks like every issue relates to features or functionality in 1.5 specifically? 

No reply required. Just scratching my head. :)

**Comment by Ver3** [comment]
@joshmarom Sorry, I do not have the page anymore. 

About feedback: Please understand many enthusiastic beta users do not know what is directly related to 1.5 or not. Speaking for just myself, I simply test the latest version of a product and then take time to post it to the dev, simply because I love their product.

I also agree with @fuzzyness I honestly would not know what point you mean exactly. Even if you point them out to me, I would still not know what this is so.

Lastly, even taking time to share this thought with you is simple due to love for the product and the people who brought it to me. No reply needed.

**Comment by arielk** [comment]
@webtikinfo if you deactivate the all other plugins (except Elementor and Elementor Pro of course) the error is still there?

**Comment by arielk** [comment]
@ver3

Thanks for your feedback.

> Cannot use responsive settings to hide a column on mobile.

True, it was never possible.

> Responsive settings are always in tab "Advanced" but not in column settings (there it is in tab 'Layout'). Strange.

We are still test this area, maybe we'll change it at all.

> When you hide something in mobile view, it is still shown (Although I can understand why from a UX point of view).

You need to click on the Preview button and then you can see the element per device

> (Box) shadow for icons still seem missing.

It's something we have not added yet.

> Column size value seems a % but this is not indicated.

Fixed!

> After entering columns size value, there seems no way to center the column again.

Unfortunately this is something we can not handle at this time, we will improve it in subsequent versions according the users feedback.

> Copy-pasting transparant color value in box shadow field of Flip box, only pastes the value partly.

It's an known issue with the native WordPress color picker. ref: #1026 & https://github.com/Automattic/Iris/issues/61

**Comment by KingYes** [comment]
@carasmo Fixed #1839

**Comment by carasmo** [comment]
@KingYes -- I don't have time to re-test for a bit. 

I don't use Divi. 

The only filter that I have to manipulate the image is this:

```
function prefix_use_product_title_for_alt_title_tags( $attr, $attachment ) {
	
    if ( ! post_type_exists( 'product' ) ) return $attr;
	        
    if ( 'product' == get_post_type() ) :
    
        $title = esc_html( get_the_title() );

        $attr['alt']   = $title;
        
    endif;
	
	return $attr;
        
}
add_filter( 'wp_get_attachment_image_attributes', 'prefix_use_product_title_for_alt_title_tags' , 20, 2 );
```

**Comment by carasmo** [comment]
Never mind, I didn't see this: https://github.com/pojome/elementor/commit/2f9cd83b09b5c100f83209fc55a93c512279bab8

**Comment by arielk** [comment]
Hi Everyone!

Elementor 1.5.0 RC2 is available for testing.

You can get it by going to Elementor > Tools > Versions, and enabling the beta tester feature. You can also follow the link below.

This version fixes a bunch of issues from 1.5.0 RC1. Thanks everyone for all your help with RC1!

Notable fixes include:

- New! - Added responsive mode for Column Width control (Including Tablet! #418)
- Tweak! - Added unit indication for Column Width / Widgets Space controls
- Fix! - Added class alias registration functionality (#1835)
- Fix! - Slick parameters for Image carousel
- Fix! - Register scripts for a relative `SITE_URL`: iris, color-picker, image edit
- Fix! - Admin settings tab in safari browser
- Fix! - Empty column view height in safari browser
- Fix! - `nofollow` Implementation
- Fix! - Minimum possible custom `z-index` is `0`
- Fix! - Reject resize column width on single column
- Fix! - Validate return image sizes date before use (#1839)
- Deprecated! - Mobile Width control is no longer supported. Please use the Column Width control in the Layout tab instead.

If you haven’t tested 1.5.0 yet, now is the time! You are invited to download the new Beta RC2 here:

https://downloads.wordpress.org/plugin/elementor.1.5.0-RC2.zip

For bugs and remarks, please reply with a comment below!

Many thanks for your support and help!

**Comment by copen8** [comment]
Possible bug in the BETA RC2!

When you add the widget called columns(nested columns) to your section there is no space. The result is that its very hard to put any widget inside the nested columns(Inner section). I attach I image that might be helpful for you to understand what I'm talking about.  

![beta_elementor](https://user-images.githubusercontent.com/22563132/27342711-3cb347b2-55e1-11e7-8874-ff029cca95ee.jpg)

**Comment by arielk** [comment]
Is it a Safari browser?

We fixed this bug in last release (`Fix! - Empty column view height in safari browser`), please check again that the plugin was updated to RC2 and try again to refresh the page and let me know if this resolve the problem.

**Comment by copen8** [comment]
Update @arielk 
1)According to wordpress its Elementor Version 1.5.0-RC2. 
2) I use google Chrome
3) I refreshed the page still the same problem

**Comment by arielk** [comment]
Sorry, Now I can confirm this bug. Thanks for your feedback!

**Comment by soyket** [comment]
Hello, I did submit a ticket few months back about adding image class (ie: <img src="xx" class="abc" ) when using the developer api I found no such way which is kinda weird! Because currently for this you can't add responsive class / any other class directly to the img tag! Do have a look at this issue 
Thanks

**Comment by copen8** [comment]
Possible bug found in Elementor RC2. I don't know yet...

@arielk 
When I use the Elementor canvas as template  it is impossible to reach and click the section settings. I took a screenshot for you to see and confirm the bug. I should point out i only experience this issue when I use Elementor Canvas Template not on standard template. 

I attach an image. I had to go to page setting and add 5px padding top, to be able to see the controls. I'm using google chrome and I tried to update the page.
A suggestion to the problem in the future might be for the section control to fold downwards (in similar fashion like ,column and widget, instead of upwards.  




![elementorbeta2](https://user-images.githubusercontent.com/22563132/27353319-ddc59246-5603-11e7-853a-85c74cbdbc5c.jpg)

**Comment by WPDevHQ** [comment]
@copen8 - This might be the same issue you are facing. Theme related!
See: https://www.facebook.com/groups/OceanWP/permalink/1382670298489119/

**Comment by JoelEadeDesign** [comment]
The new Column settings are great! Well done.

My notes from having poke around:

1. I'd prefer there not to be animation of the icons when hovering on the **Column** settings, so they appear instantly. It feels slower when there's a delay, however, I like the delay when you no longer hover and the icons stay for half a second then hide. Seeing as the icons are now smaller it's harder to stay on the icons when hovering, so the delay before hiding them is welcome.

2. The **Section > Structure** settings don't go the full width of the sidebar:
![image](https://user-images.githubusercontent.com/1729832/27365668-9e642712-5684-11e7-95e9-323d417a804a.png)

3. The **Column > Layout > Content Position** doesn't seem to be working for the **Column** element. The second column in this image 
![image](https://user-images.githubusercontent.com/1729832/27365952-71c38a16-5686-11e7-8e2e-5868d54cfe6a.png)
, with the green background, has a **Content Position** of **Bottom** yet the content remains at the top.

Again, great work. Looking forward to this release!

**Comment by evyatar2722** [comment]
how can i use the new beta?

**Comment by arielk** [comment]
@evyatar2722 As we wrote above you need to download the new Beta RC2 here: https://downloads.wordpress.org/plugin/elementor.1.5.0-RC2.zip

@JoelEadeDesign

1. While working on this version, we created a number of sketches as you suggest, but unfortunately we were unable to reach a satisfactory result. So for now we are testing some other directions to create a better workflow in the next versions. 

2. Thanks for your report!

**Comment by anandau** [comment]
In one of my Elementor Addon, i am using Elementor's js hook.

Sample Code
```
elementorFrontend.hooks.addAction( 'frontend/element_ready/ae-woo-tabs.default', function( $scope ) {

   // some code here

});
```


In earlier version (till 1.4.9) it is working fine but now in 1.5 RC2 it is following throwing error. 
`"Cannot read property 'addAction' of undefined"`

It this a bug or there is some change in JS hook api. 
I checked the docs section but couldn't find any change.

**Comment by KingYes** [comment]
@anandau 

You need wrap your code by this:

```
$( window ).on( 'elementor/frontend/init', function() {
    // Here write your code...
} );
```

**Comment by anandau** [comment]
@KingYes 
Thanks a lot. Issue resolved :)

**Comment by anandau** [comment]
@KingYes 
Your suggestion is working fine on frontend. 
But in 1.4.9  same script was also working for editor preview. 
Do i need to make any changes to make it working in editor preview.

**Comment by anandau** [comment]
@KingYes 
Let me be precise about my issue. 

Above hook runs everytime my preview is refreshed. Like if i make any changes in my widget settings, it refresh the preview and above mention hook is trigerred.  That's exactly as expected.

But now if i open my already elementor created page in editor, this hook is not triggered in initial load. 
I have to click on some setting in options panel to trigger preview refresh and then this hook is triggered. 

Is there any way  that my code can also trigger when page is initially loaded in editor.

**Comment by arielk** [comment]
Hi Everyone!

Elementor 1.5.0 RC3 is available for testing.

You can get it by going to Elementor > Tools > Versions, and enabling the beta tester feature. You can also follow the link below.

This version fixes a bunch of issues from 1.5.0 RC2:

- Tweak! - Limit up to 100 revisions to display in the panel
- Tweak! - Setting Buttons size slightly increased (https://github.com/pojome/elementor/issues/1827#issuecomment-307973797) thanks @LearnWPBasics 
- Fix! - Bug Image Carousel widget in RTL direction
- Fix! - Structure control view UI glitch (https://github.com/pojome/elementor/issues/1827#issuecomment-309953788) thanks @JoelEadeDesign
- Fix! - Empty columns widget view min-height (https://github.com/pojome/elementor/issues/1827#issuecomment-309804647) thanks @copen8

If you haven’t tested 1.5.0 yet, now is the time! You are invited to download the new Beta RC3 here:
https://downloads.wordpress.org/plugin/elementor.1.5.0-RC3.zip

The release is scheduled for Wednesday, June 28, 2017, so if you found any bug or error, please reply with a comment below!

Many thanks for your support and help!

**Comment by arielk** [comment]
V1.5 finally released. Thanks everyone!!

**Comment by carasmo** [comment]
Really great! I would only make the selectors larger. I did it with CSS and the user can click an option which changes the body class for admin users.

![screen shot 2017-06-28 at 8 59 57 am](https://user-images.githubusercontent.com/1124594/27638228-8aaad46c-5be0-11e7-9eb3-4577c4eb9fd9.png)


```

.elementor-view-helper.elementor-editor-active .elementor.elementor-edit-mode .elementor-editor-element-setting {
    font-size: 18px;
    width: 45px;
    height: 45px;
}

.elementor-view-helper.elementor-editor-active .elementor.elementor-edit-mode .elementor-editor-element-settings {
    height: 45px
}

```

**Comment by crsmoore** [comment]
I think that's too big Christina.

Maybe the team could add a control in Elementor > Settings or Tools that allows a certain range, which wouldn't break the Editor? 




~~ Sent from an iPhone ~~

**Comment by carasmo** [comment]
Since they are positioned absolute, it doesn't break the editor. And, though I haven't used Elementor on the iPad, 44px is the min. recommended for fingers. 

I like it bigger, but with my settings, it's a choice if the user doesn't like it, he or she can turn it off and go back to the 26px.

**Comment by crsmoore** [comment]
I didn't say yours broke the editor. :) 

Just suggesting the team provide a range in Elementor > Settings that would allow people to choose their own number within a preapproved range that wouldn't break the Editor at all or mess up how it looks.

~~ Sent from an iPhone ~~

**Comment by carasmo** [comment]
That's a good idea!

**Comment by Ver3** [comment]
@carasmo Thank you for the snippet, I've added it to our Community Board with shared resources:

https://trello.com/c/X4fNFqKW

@arielk and everyone at Elementor: Congratulation, truly awesome update! Thank you for letting me part of this beta.

**Comment by LearnWPBasics** [comment]
Ver3 - I already had this back on the 20th and posted it in the E FB gorup :)
http://snifflevalve.com/enhance-display-of-editor-items-in-elementor-1-5/

Cheers!
Lyle

**Comment by Ver3** [comment]
@LearnWPBasics Apologies Lyle, there's just so much info Lately, it's hard to keep the Board updated. I wish I had an intern :-)

Updated the card though! https://trello.com/c/X4fNFqKW

**Comment by JoelEadeDesign** [comment]
Having to hover the Edit icon to see the Column and Element editing icons really bugs me (feels slower and unintuitive) so I've added this to my style sheet:
`.elementor-editor-active .elementor.elementor-edit-mode .elementor-editor-element-settings .elementor-editor-element-trigger:not(.elementor-active)~.elementor-editor-element-setting {
	width: 25px !important;
	font-size: 11px !important;
}`

**Comment by LearnWPBasics** [comment]
Joel - thank you so VERY much for this! Works perfectly 👍 

I have no idea why they decided to go with the hover idea; a step backwards in workflow. Never really noticed the reverse order of the element icons until you mention it; great to have it reversed now and consistent with the Sections.

Would you mind if I added this to the Quick Tip to enhance the display of editor items that I noted above? I will definitely make note of the source :) 

Cheers!
Lyle

**Comment by JoelEadeDesign** [comment]
Hey @LearnWPBasics :) Awesome. Glad you liked the tweaks. Feel free to use it however you like :) Cheers mate

**Comment by LearnWPBasics** [comment]
Thanks Joel! :) Will update the post now :)

**Comment by sicuro** [comment]
<img width="1468" alt="captura de tela 2017-06-29 as 01 16 31" src="https://user-images.githubusercontent.com/2956798/27671200-a3e8b25e-5c68-11e7-8951-c6e6d680f833.png">

I update my plugin, but, right now, scripts functions do not working... how i solve that?

**Comment by Ver3** [comment]
@JoelEadeDesign Thanks for the snippets, very helpful. Ive added them to this card:

https://trello.com/c/X4fNFqKW

@LearnWPBasics This time I immediately included your link ;-)
