### ISSUE TITLE
Elementor 1.6 - Beta Release (RC4 updated)

### ISSUE THREAD

**Issue by arielk** [pojome/elementor#2077]
===========
## [RC4 UPDATED - PLEASE READ BELOW!](https://github.com/pojome/elementor/issues/2077#issuecomment-318915347)
===========

Hi everyone,

We have been working on version 1.6.0 for several weeks now, and are excited to share with you some of the new improvements.

We'd appreciate if you could spare a few minutes and test the new features out.

If you still haven't enabled beta testing in Elementor, please follow these steps:

1. Go to Elementor > Tools > Versions
2. Enable the beta tester feature
3. Go to Dashboard > Updates and update to the latest beta version

This will get you testing the new Elementor 1.6.0 RC4.

**Let's review the changes we have introduced:**

### Image Lightbox
Back in version 1.3, we introduced the video lightbox. Now, we are introducing one of the most requested features: image lightbox, used for images and galleries.

Starting with this version, all links that point to images will automatically popup with lightbox.

You can set the lightbox popup per widget, and can customize it with Elementor. The lightbox is fully responsive and works on every device.

### Text Shadow
Another control added in this version is text shadow. With this feature, you can add a shadow to your text elements.

Right now this feature is only available for the Heading widget. You are welcome to try it out.

### Editor Loading
A huge feature in this release is actually under the hood. This feature will solve issues that some of our users come across.

Until now, when you click on 'Edit with Elementor', the editor would open with the slug: 
`your-domain.com/?elementor`

From this version on, the loading of the editor will be done on the wp-admin framework and not on the frontend of the site, and the slug will appear like this: 
`your-domain/wp-admin/post.php?post=POST_ID&action=elementor`

This change will help solve many common problems such as: memory issues, conflicts with mod security, SSL on the dashboard only (for sites on WPEngine for example), conflicts with Front Page and several other issues.

### Global Settings
With this version, we've added an option to control the general design settings from inside the panel.

If you click on the hamburger icon > Page Settings, you can control the page settings with a preview in the editor.

### My Library
- We've added a bulk option for import and export of several templates, via a ZIP file.
- We've added access to the template library for users with `edit_pages` capability.

### Instructions what exactly to do:
- Please review the new features carefully, preferably on your staging sites and not in production.

- If you are using Elementor Pro, _please update to the latest 1.5.8 version_ for maximum compatibility.

- Get the new version by going to Elementor > Tools > Versions, and enabling the beta tester feature and you can get notification to update it.

- You can also download the new version here: https://downloads.wordpress.org/plugin/elementor.1.6.0-RC4.zip

- Designated time for release: August 2, 2017

**For bugs and remarks, please reply with a comment below!**

Many thanks for your support and help!

[Elementor Beta - Sign Up Now For Our Elite Group Of Early Access Testers](https://my.elementor.com/beta/)

**Comment by WPDevHQ** [comment]
Sorry guys but here's issue #1 

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\wamp64\www\wordpress\wp-content\plugins\elementor\includes\template-library\sources\local.php on line 354

**Comment by WPDevHQ** [comment]
Switched PHP from v5.6.x to v7.0.x resolved the issue!

**Comment by anandau** [comment]
@arielk Does it mean there is change in minimum php version requirement for Elementor. 
if yes can you mention those change exactly.

**Comment by arielk** [comment]
@WPDevHQ Where did you get this error?

@anandau Today these are our requirements: https://docs.elementor.com/article/38-requirements
I do not think this is going to change, but I hope we'll experience less memory issues.

**Comment by badcat** [comment]
I'm not seeing the Lightbox working.  I initially made shure to check "Image Lightbox" in the settings, and it's snot working, then after specifically choosing the Lightbox "Yes" option on the element and verifying the data-open-lightbox="yes" is added, I still get only the full resolution image loaded directly.  What JS file/s was updated?

**Comment by WPDevHQ** [comment]
@arielk The error appears sitewide - initially I thought it was only the editor but having reverted back to PHP v5.6.25 I'm seeing it sitewide!

**Comment by KiQdev** [comment]
Tried on 3 sites, different themes, but breaks post widget and display the posts under each other. 
Lightbox needs a close button, and would be nice to have it as carousel:-)

**Comment by Rafava** [comment]
The lightbox is really nice! Wouldn't work on theme Hestia, but worked totally fine with OceanWP. I couldn't see the text shadow option anywhere. Preview in page settings loaded fast 👍

**Comment by JoelEadeDesign** [comment]
Looking forward to this release. Well done!

Unfortunately the image lightbox doesn't work for me. The image, linked to Media File, opens in the browser window. No js errors either. Attached are my system specs [elementor-beta.txt](https://github.com/pojome/elementor/files/1174749/elementor-beta.txt):

Cheers!

**Comment by Manuel-SG** [comment]
Lightbox is not working. I tried with Twentyseventeen Theme and with Astra. No luck. Only active plugins are Elementor and Elementor PRO and Astra Addon. I activated lightbox in setup. On Images themselves I chose "yes", "no", and "default". No Luck. Single Image, Image Gallery and Text with embedded Image. No Luck. I also tried with deactived PRO plugin and deactivated Astra Addon. Still no lightbox.

See here: https://pagebuilder.demo.site/lorem/

Tech Specs:

Server Environment |   |  

Operating System: | Linux |  
Software: | nginx/1.12.0 |  
MySQL version: | 5.5.5 |  
PHP Version: | 7.0.18-1~dotdeb+8.1 |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
Elementor Library: | Connected |  


Active Plugins |   |  
-- | -- | --
Astra Pro - 1.0.0-beta.5 | By Brainstorm Force |  
Elementor - 1.6.0-RC1 | By Elementor.com |  
Elementor Pro - 1.5.8 | By Elementor.com

Version: | 4.8 |  
-- | -- | --
Site URL: | https://pagebuilder.demo.site |  
Home URL: | https://pagebuilder.demo.site |  
WP Multisite: | No |  
Max Upload Size: | 256 MB |  
Memory limit: | 128M |  
Permalink Structure: | /%year%/%monthnum%/%day%/%postname%/ |  
Language: | en-US

**Comment by Manuel-SG** [comment]
Update: I can also report the bug of "broken post elements", like KiQdev 
--> this should be 3 columns, but its only one : https://pagebuilder.demo.site/posts/

**Comment by badcat** [comment]
I know this is a beta but here's a Feature Request / Suggestion.  Imagine the possibility of the Pro version having MULTIPLE Text Shadows? (like so... https://codepen.io/chriscoyier/pen/urkCd ) Having an interface with a Plus/Minus to **Add or Remove** as well as **Reordering** the shadow layers.  Cool.   

![shadow](https://user-images.githubusercontent.com/26096/28624372-f227f02c-71e6-11e7-8100-c4bf62a09bb4.png)

**Comment by arielk** [comment]
We just released a new beta version, please update your version to v1.6.0 RC2:

- Fix a spelling error in Lightbox JS
- Fix for PHP < 7
- Fix Posts widget 

Please update or download the new version here: https://downloads.wordpress.org/plugin/elementor.1.6.0-RC2.zip

Thanks everyone for your help and feedback!

**Comment by KiQdev** [comment]
That fixed the Post widget problem:-) but still see this in several themes based on Underscores. my own theme, and also themes like Astra and Astra Pro.
I don´t know, but maybe that is something that comes from the code in Underscores, haven´t had time to check it really.
TypeError: this.elements.$posts.imagesLoaded is not a function

**Comment by avermat** [comment]
I tried the bulk template import using a zip file, but when I click "Import Now" nothing happens. The "My Library" page refreshes, but none of the json templates appear in the library.

**Comment by Manuel-SG** [comment]
Ok, Lightbox is working now. So - there are no "captions" or any text displayed in the lightbox - just the image, right?
Post Grid seems to be working, too.

**Comment by JoelEadeDesign** [comment]
Image Lightbox is fixed for me too, thanks. 

A few comments:
1. Is there a reason why the **Content Width** doesn't apply to images. I'd like the option to be able to scale the width up to 100% of the screen width. I can understand if the padding allowed the overlay to be clicked to close but one has to click the X to close the lightbox. I can remove the padding easily enough but 
![image](https://user-images.githubusercontent.com/1729832/28648460-49a100f8-72b1-11e7-9723-4ff63ee977c5.png)

2. I've noticed that there's a longer delay between typing in an element, a **Text Editor** for example, and the content updating in the live preview area. It used to be negligible but now it's a noticeable half second delay.

3. The **Style** tab for the **Video** is empty. I'd suggest removing it to avoid confusion.

4. The **Video** element no longer opens in the Lightbox, and there's a JS error: 
![Uploading elementor--video-lightbox.gif…](Video Overlay error)

5. I know I've mentioned it before but the animated icons for the **Column** and **Element** bug me. The **Section** icons are all visible, why not the **Column** and **Element**? It makes editing slower IMO.

6. The order of the editing icons are the same for **Sections** and **Columns** but reversed for **Elements**. I found that a little jarring. I've added my own CSS to change it, as well as for my above comment, but thought I'd let you know my thoughts in case anyone else agrees.

I like the new solid icons BTW. Much easier to interpret quickly :) 

Thanks!

**Comment by WPDevHQ** [comment]
PHP version issue resolved, thank you team 👍

**Comment by arielk** [comment]
@KiQdev Is the problem related to version 1.6?

@avermat Did you get any error?

@Manuel-SG Right now it's just a lightbox without captions, but maybe we'll add it in the future.

@JoelEadeDesign
1. We removed this option for next beta version (RC3). Originally it was designed for video, but apparently it only confuses the users.

2. You're right, we'll check it

3/4. Fixed

5/6. For now we have no better way of displaying it, but we are constantly improving the interface, so I estimate it will change in the future.

Thanks

**Comment by KiQdev** [comment]
@arielk It must be related to version 1.6Pro+1.8, I don´t have the problems on the other sites with 1.5.5+Pro1.5.8. I will check more a little later.
Also noticed now that SmartSlider don´t show up anymore, just blank page, same when Astra theme. Works with Twentyseventeen. So not sure what is causing it yet.

**Comment by arielk** [comment]
## v1.6 Beta Version RC3

We just released a new beta version, please update your version to v1.6.0 RC3:

- Fix mobile video width 
- Fix video lightbox errors 
- Fix bulk export for empty templates
- Removed content width control in the global settings / lightbox for better understanding 

Please update or download the new version here: https://downloads.wordpress.org/plugin/elementor.1.6.0-RC3.zip

Thanks everyone for your help and feedback!

**Comment by avermat** [comment]
@arielk No error message: https://www.dropbox.com/s/88wmu15l1uav9bc/bulk-import.mp4?dl=0 (video is using RC3)
Sys info: https://www.dropbox.com/s/lhrx2vkxjmt2wi2/system-info-divi03.com-27-07-2017.txt?dl=0

**Comment by drawcard** [comment]
The lightbox feature is fantastic - but my only comment is that it should be disabled in the Elementor editor itself. For instance, if I am working on an Image Gallery widget and I happen to click on one of the container images, the lightbox plugin triggers and I have to close it to continue editing the page.

**Comment by JoelEadeDesign** [comment]
@drawcard I understand what you mean. I'm used to clicking anywhere in an element to edit it. I've had to remember to click the Edit (pencil) icon instead. This also applies to the Video element, as clicking anywhere on the video triggers the play action.

It is necessary though, as without triggering the lightbox within the Elementor editor you're unable to see the style changes made in the **Global Settings > Lightbox** area.

**Comment by drawcard** [comment]
@JoelEadeDesign perhaps a solution is that when you head over to Global Settings > Lightbox, the lightbox displays with a dummy image inside it, so customisations can be made. But when in regular edit mode it's disabled, so it's easy to navigate around it without accidentally triggering it all the time. This is the sort of behaviour that's used for the Flipbox widget when you want to edit the reverse side of a card, for example.

I guess everyone's case is different but I am putting together image-heavy pages for design portfolios like: https://drawcard.com.au/project/icac-brand-strategy and to navigate around some of those larger image gallery blocks, I have to click inside the gutters of the image gallery to avoid triggering the lightbox effect.

**Comment by drawcard** [comment]
Unrelated to the above - I'm reporting a JS problem I'm having with Swiper:

![image](https://user-images.githubusercontent.com/1435638/28698053-ccefad78-737f-11e7-8a3f-bfff694351d4.png)

![image](https://user-images.githubusercontent.com/1435638/28698072-eefa0300-737f-11e7-8ded-c95af0a69cf9.png)

**Comment by JoelEadeDesign** [comment]
Yeah, that's a possible solution. Beautiful site, BTW :)

**Comment by Lageeek** [comment]
The lightbox is working for me, but it has a conflict with a gallery plugin, so I had to deactivate it. It would be also nice, if the lightbox would close when you click on the background.

You changed the editor url, but unfortunately this does not solve the issues with buttons from other plugins in the text editor. E. g. Types (Toolset) inserts a buttion in the Texteditor, without Elements, this works fine, but with Elements the button is not visible in the Texteditor. Other buttons (e.g. 2JGallry, or Nextendslider) are visible in Elementor -> text editor, but don't open - no reaction.

**Comment by drawcard** [comment]
@Lageek point 1) Yep I think there's probably a conflict with my theme somewhere. For some reason the same thing happens with the Carousel galleries (that use Slick.js) as raised in #1607.

point 2) This caught me off guard as well. I also the use Pods plugin on some sites and though the Pods Shortcode button displays in the Text Editor widget interface, clicking on it only loads a modal dialog box with nothing inside.

**Comment by Lageeek** [comment]
@drawcard, yes I have experienced, that this is a general problem of the text editor mode in Elementor. I had tested several plugins with shortcode buttons, either they were unvisible or they did not open. If you switch to "back to wordpress editor" all of them work without any problem.

**Comment by eder-tuffic** [comment]
Here when you click Back to Panel, reload the page and not return. (Version RC3)

**Comment by purbeckpixels** [comment]
Similar issue as @eder-tuffic - editing a Page with 1.6 RC3 doesn't show the correct Page Settings (tried to edit the Page Settings of a Page called 'About' that has the ID 335, but Page Settings is showing an Events Calendar plugin CPT with the ID of 865, and View Page and Return to Dashboard also opens/returns to the Event with ID 865). I've rolled back to 1.5.5 for now because I don't want to risk the work I've done on the dev site.

**Comment by purbeckpixels** [comment]
Gave RC3 another go to see if I could work out what's going on. Page Settings (like Title) were being taken from one of three Event CPTs (the last three planned, but not the last three entered) no matter which Page I chose to edit with Elementor. Elementor isn't enabled for Event CPTs, it's only enabled for Pages. Disabling The Events Calendar (by Modern Tribe) plugin fixed the issue, but then I reactivated it and disabled The Events Calendar Shortcode plugin (not developed by Modern Tribe) and the issue again was fixed. So it seems that there's some kind of conflict between RC3 and [The Events Calendar Shortcode plugin](https://wordpress.org/plugins/the-events-calendar-shortcode/) (NOT The Events Calendar plugin) which, incidentally, is being used on every Page via Elementor's Shortcode widget. Got there in the end.

**Comment by KingYes** [comment]
@purbeckpixels In empty page, the page setting is correct? If yes, please deactivate all your plugins, and try again..

**Comment by purbeckpixels** [comment]
@KingYes After doing some more testing (I deactivated all plugins and narrowed it down to The Events Calendar Shortcode plugin yesterday) any page that doesn't use the TECS plugin to output a list of upcoming events works fine, the Page Settings Title and View Page/Return to Dashboard URLs are correct.

**Comment by Manuel-SG** [comment]
Please check your "Nagging Screen" ("Do you want to help? Collect anonymous data..."). It reappears in RC3. And whatever I try to click (yes or no), the screen is not going away.
I just deactived the RC3 and activated v1.5.5. With that I was able to close the "nagging screen" (the choice was saved). After that I reactivated v1.6 Beta RC3. Until now, the nagging screen is not to be seen. But I will keep an eye on it :-)

**Comment by arielk** [comment]
## v1.6 Beta Version RC4

Please update your version to v1.6.0 RC4:

- Fix conflict with plugins that change the global post (@purbeckpixels)
- Added control option to enable/disable lightbox on the editor (@drawcard, @JoelEadeDesign)

Link to download: https://downloads.wordpress.org/plugin/elementor.1.6.0-RC4.zip

Thanks everyone for your help and feedback!

**Comment by purbeckpixels** [comment]
@arielk Thanks. Fixed.

**Comment by Manuel-SG** [comment]
No (new) bug - just a question: will the forthcoming Elementor v1.6 still be usable with php 5.6 ? 
Was that being fixed in RC2 with the "Fix for PHP < 7" ???

**Comment by arielk** [comment]
@Manuel-SG There is no change in requirements and there is full compatibility with PHP 5.6 (of course we recommend 7 or higher). We just added a small patch for older PHP versions...

**Comment by buzanman** [comment]
Tested new features, and works well! I am running on local by flywheel on PHP 7, MySQL 5.6, nginx.
What I would say is can you disable the lightbox from working in editor mode it gets quite annoying popping up when you select the image you want to edit?

**Comment by purbeckpixels** [comment]
@buzanman This functionality was added in RC4. When editing a page, go to [hamburger menu top-left] Global Settings > Lightbox and disable Enable In Editor. Works for me.

**Comment by buzanman** [comment]
Sorry ignore last comment I just realised you have put a disable light box setting in global page settings.

**Comment by arielk** [comment]
v1.6 is here!

Thanks everyone for your help!!
