### ISSUE TITLE
Text Editor broken after update to 1.6

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#2125]
## Description

There are several people also reporting at https://wordpress.org/support/topic/cant-view-editor-in-1-6-after-update/#post-9374375

Basically, the text editor displays no text whether viewing the visual or text tab. Can’t edit at all until this is fixed.

![text-editor-bug](https://user-images.githubusercontent.com/974442/28886572-d58ff422-776e-11e7-88e7-6a3c54072a3d.png)

## Steps to reproduce

upgraded to Version 1.6.0

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.6.32
	PHP Version: 5.6.31-2+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.8
	Site URL: https://staging.ucsflibrary.flywheelsites.com
	Home URL: http://staging.ucsflibrary.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Dynamik-Gen
	Version: 2.2.1
	Author: The Cobalt Apps Team
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 2.5.2
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 3.3.3
		Author: Automattic

	Breadcrumb NavXT
		Version: 5.7.1
		Author: John Havlik

	Compress JPEG & PNG images
		Version: 2.2.4
		Author: TinyPNG

	Elementor
		Version: 1.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 1.5.8
		Author: Elementor.com

	Genesis Dambuster
		Version: 1.6
		Author: Russell Jamieson

	Graceful Email Obfuscation
		Version: 0.2.2
		Author: Nicholas Wilson, Jason Hendriks

	Insert Pages
		Version: 3.2.2
		Author: Paul Ryan

	Jetpack by WordPress.com
		Version: 5.1
		Author: Automattic

	LH HSTS
		Version: 1.21
		Author: Peter Shaw

	LibCal Hours for WordPress
		Version: 1.0.1
		Author: Stefan Topfstedt

	Loginizer
		Version: 1.3.5
		Author: Raj Kothari

	Redirection
		Version: 2.6.6
		Author: John Godley

	Relevanssi
		Version: 3.5.11.1
		Author: Mikko Saari

	Sticky Menu (or Anything!) on Scroll
		Version: 2.0.1
		Author: Mark Senff

	TablePress
		Version: 1.8
		Author: Tobias Bäthge

	TablePress Extension: Column filters
		Version: 0.9.2
		Author: Stefan Topfstedt

	TablePress Extension: Shortcode Attributes Plus
		Version: 0.9.0
		Author: Stefan Topfstedt

	UCSF Library Search Filter
		Version: 1.0.0
		Author: Stefan Topfstedt

	User Role Editor
		Version: 4.35.3
		Author: Vladimir Garagulya

	WordPress Importer
		Version: 0.6.3
		Author: wordpressdotorg

	WPForms
		Version: 1.3.9.1
		Author: WPForms

	WPForms MailChimp
		Version: 1.1.1
		Author: WPForms

== Debug ==
	Errors: 
		ReferenceError: tablepress_editor_button is not defined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/tablepress/admin/js/tinymce-button.min.js?wp-mce-4603-20170530 - 1:253
			2017-08-02 17:30 +00:00

		TypeError: Cannot set property 'onload' of null
			at https://staging.ucsflibrary.flywheelsites.com/wp-includes/js/tinymce/tinymce.min.js?ver=4603-20170530 - 11:19927
			2017-08-02 17:05 +00:00
			x 4 times

		TypeError: Cannot read property 'removeClass' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
			2017-07-26 19:42 +00:00

		ReferenceError: summonWidget is not defined
			at https://staging.ucsflibrary.flywheelsites.com/?elementor - 1:1
			2017-07-26 00:27 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.5 - 5:11873
			2017-07-21 18:30 +00:00
			x 2 times

		ReferenceError: summonWidget is not defined
			at https://staging.ucsflibrary.flywheelsites.com/?elementor - 1:1
			2017-07-18 17:17 +00:00

		TypeError: Cannot read property 'removeClass' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.5.2 - 5:11873
			2017-07-03 23:22 +00:00

		TypeError: Cannot read property 'holdReady' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.10 - 3:2806
			2017-06-27 22:33 +00:00

		TypeError: Cannot read property 'holdReady' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.8 - 3:2806
			2017-06-15 21:57 +00:00
			x 3 times

		TypeError: elementorFrontend.getScopeWindow(...).jQuery is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.8 - 6:22116
			2017-06-15 20:14 +00:00
			x 4 times

**Comment by KingYes** [comment]
Fixed by https://github.com/pojome/elementor/commit/8e67b1d7b0b44d57cfb83574008ae25a48044f6a

Thanks!

**Comment by mizejewski** [comment]
Just tested again after de-activating Jetpack and the problem remains.

**Comment by mizejewski** [comment]
Just updated to Elementor 1.6.1 with high hopes, but the text editor problem remains 🙁

**Comment by KingYes** [comment]
@michelgotta please deactivate all other plugins..

**Comment by mizejewski** [comment]
Rolled back to Elementor 1.5.5 and everything works again.

**Comment by mizejewski** [comment]
FYI @KingYes: When I deactivate the <a href="https://wordpress.org/plugins/tablepress/" target="_blank">TablePress</a> plugin, the Elementor 1.6.1 text editor does not break.
