### ISSUE TITLE
[BUG] Shape Divider not showing

### ISSUE THREAD

**Issue by dave-hiddendepth** [pojome/elementor#2580]
## Description

Shape Divider not showing in the latest update. 

## Steps to reproduce

Enable Shape Divider top or bottom

## Environment

TypeError: jQuery.get is not a function
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.7.11 - 2:13452
2017-10-12 21:23 +00:00
x 6 times

TypeError: jQuery.get is not a function
at https://hiddendepth.ie/wp-content/plugins/elementor-extras/assets/js/frontend.min.js?ver=1.5.0 - 1:6841
2017-10-12 20:21 +00:00
x 13 times

TypeError: jQuery.get is not a function
at https://hiddendepth.ie/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=1.7.11 - 2:13452
2017-10-12 20:13 +00:00

**Comment by arielk** [comment]
Can you share with us a link to this page?

**Comment by dave-hiddendepth** [comment]
This page shows on frontend https://hiddendepth.ie/does/web-design/

But does not reflect preview in the admin area. 
Still does not show after saving, refreshing, clearing all caches, etc.
![2017-10-16_12-56-29](https://user-images.githubusercontent.com/1297728/31610825-7a3f26ae-b271-11e7-88d5-22fed516892d.jpg)

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by dave-hiddendepth** [comment]
Happy to carry out any instructions you provide but won't be giving login details to my site.

**Comment by DerekBess** [comment]
We too have the same exact issues. This is due to the CSS not outputting border-style: solid.

I fixed this by manually adding styles to my theme project.

**Comment by manasmdg3** [comment]
> We too have the same exact issues. This is due to the CSS not outputting border-style: solid.
> 
> I fixed this by manually adding styles to my theme project.

How can I solve this? A little assist please @Creativenauts

**Comment by arash88** [comment]
Bottom Shape dividers are still not showing. Latest Elementor Pro without any other plugins. v3.7.1 + v3.6.5
