### ISSUE TITLE
Issue with preview and page templates

### ISSUE THREAD

**Issue by rtthemes** [pojome/elementor#3933]
When the "Preview changes" button clicked, it resets the page template selection and saves for permanently.  Here is a screencast for better explanation https://cl.ly/3J2H2p3R0m46

**Comment by bainternet** [comment]
@rtthemes 

Thanks for reporting, fixed in 2.0.2

**Comment by simplicity17** [comment]
This is still happening to me even after the 2.0.2 update. I am using the GeneratePress theme with Elementor Pro.

**Comment by Hunuke** [comment]
Same here, with 2.0.2. I did a rollback to 1.9.8 and updated to 2.0.2 from there, now it's working. But I have to assign "Elementor Canvas" to all posts again, saved prior the 2.0.0 version.
