### ISSUE TITLE
[Bug] Divider for Post Info position is fixed, but the style doesn't work because it's applied to the top border instead of the left border

### ISSUE THREAD

**Issue by chemocool** [pojome/elementor#4231]
## Description

with Elementor Pro 2.0.3

Divider for Post Info position is fixed, but the style (dashed, dotted etc) doesn't work because it's applied to the top border instead of the left border.

## Steps to reproduce

1. Drag a Post Info widget
2. Have 2 or more items in it
3. Set divider to dashed
4. It sets **border-top-style: dashed** instead of **border-left-style: dashed**

in _.elementor-icon-list-item:not(:last-child)::after_

**Comment by bainternet** [comment]
@chemocool 

make sure you clear your browser cache ( JS/CSS ), beacuse its fixed in 2.0.8 and pro 2.0.3

**Comment by chemocool** [comment]
My browser cache is refreshed, i have the latest version of both Elementor (2.0.8) and Elementor Pro (2.0.3).

I still see **border-top-style: dashed** instead of **border-left-style: dashed**.

The bug I logged at first concerning Post Info Divider was fixed (i can see the fix), but the style is applied to the top border instead of the left one.

I had 2 colleagues that just saw the bug loading the page for the first time (so not cached).
