### ISSUE TITLE
Multisite: Elementor requires PHP version 5.4+, plugin is currently not active.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#438]
Hi

I was going to test out Elementor with a multisite using WP version 4.6.
I activated the plugin and received this warning message:
Elementor requires PHP version 5.4+, plugin is currently NOT ACTIVE.

Notice the screenshot:
First the warning message then right below it says Plugin activated.
Looking at the Installed plugins list Elementor is activated as it says Deactivate in the list.

![screen shot 2016-08-20 at 03 03 22](https://cloud.githubusercontent.com/assets/5323259/17827763/f5863f6e-6682-11e6-868e-3fde111651bb.png)

**Comment by lunacroft** [comment]
@paaljoachim you need to change PHP version in your host provider, I did it here. If your host uses Cpanel, go to PHP Configuration, choose version and click update =)

**Comment by paaljoachim** [comment]
Thanks Lunacroft! I logged in and adjusted the version to 5.6.24. I could probably have changed it to 7.0.9. But I thought I might as well stay one version behind. (I really have no idea in regards to which version to select.)

The bug I referred to is that it says it is deactivated but shows - deactivate below the Elementor title. Showing that it is activated and that one can deactivate it. If it was really deactivated (which it is) then the text below Elementor should say Activate.

**Comment by lunacroft** [comment]
Great! =)

**Comment by KingYes** [comment]
Please create new file as `phpinfo.php` and write this:
```
<?php
phpinfo();
```

Open this file with your browser and see what is the REAL PHP version of your server..

**Comment by yehudah** [comment]
@paaljoachim 
I understand the issue has been solved.
If you need more help with this issue feel free to reopen.

**Comment by griotsarts** [comment]
I have the same issue but for a single wordpress install. I did update the PHP at my service provider's site. I still see the message that the plugin is deactivated.

**Comment by ewordjeff** [comment]
I also have the same problem pls help me out ....am using wamp server

**Comment by Sibabale** [comment]
I have the same error but I am using localhost.

**Comment by KingYes** [comment]
If you see this notice, so your PHP server is `< 5.4`. You can check this by `phpinfo()`.

**Comment by i3130002** [comment]
Getting the same Error on php 7.0 

> Elementor requires PHP version 5.4+, plugin is currently NOT ACTIVE.

**Comment by vincentkondeng** [comment]
@lunacroft  Thank you. You helped.
