### ISSUE TITLE
ReferenceError: elementor is not defined

### ISSUE THREAD

**Issue by bogdandynamic** [pojome/elementor#4488]
Hi. After updating WordPress to 4.9.5 and now 4.9.6 I started to get these tow errors in JS console in all browsers:
```
Uncaught ReferenceError: elementor is not defined
    at i.addEditorListener (frontend.min.js?ver=2.0.12:2)
    at i.__construct (frontend.min.js?ver=2.0.12:2)
    at i.r (frontend.min.js?ver=2.0.12:2)
    at i (frontend.min.js?ver=2.0.12:2)
    at i [as constructor] (frontend.min.js?ver=2.0.12:2)
    at new i (frontend.min.js?ver=2.0.12:2)
    at t.exports (frontend.min.js?ver=2.0.12:2)
    at s (frontend.min.js?ver=2.0.12:2)
    at Object.doAction (frontend.min.js?ver=2.0.12:2)
    at n.runReadyTrigger (frontend.min.js?ver=2.0.12:2)

Uncaught Error: Uncaught ReferenceError: elementor is not defined - https://www.example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.0.12: 2
    at Object.error (main.js?ver=1.0.7:1)
    at m.win.onerror (main.js?ver=1.0.7:1)
```

None of the other plugins in WordPress were updated in the meantime, so I guess it's just a problem with the WordPress integration for Eleementor. Can someone help ?

Thank you!

**Comment by ralbatross204** [comment]
I'm seeing this too and would like to know how to fix it.

**Comment by Jenksc2** [comment]
I fixed mine by going through and deleting sections one at a time until I found the section creating the problem. Remade that section and problem went away. (save page as template before)

**Comment by arielk** [comment]
Please try to update to the latest version of Elementor and let me know it solved the problem.

**Comment by stefanpejcic** [comment]
**Still having this issue**

Uncaught ReferenceError: elementor is not defined
    at r.initEditorListeners (frontend-modules.min.js:2)
    at r.getEditorListeners (frontend-modules.min.js:2)
    at r.addEditorListeners (frontend-modules.min.js:2)
    at r.__construct (frontend-modules.min.js:2)
    at r.u (frontend-modules.min.js:2)
    at r (frontend-modules.min.js:2)
    at r [as constructor] (frontend-modules.min.js:2)
    at new r (frontend-modules.min.js:2)
    at e.exports.addHandler (frontend.min.js:2)
    at e.exports (frontend.min.js:2)

**Comment by BukkoBekka** [comment]
Hi, 

i had the problem as i was collaborating with a copywriter. He copied from the inside of elementors preview-window and pasted it into the text-field editor.

Nobody will see that there is elementor-raw-code in a text-field. By default the text-field is open with the [visual]-tab. Just open [text]-tab and search for elementor-html-code because that can cause elementor behaves with that error. At least thats how i fixed the problem.

kind regards
andre

**Comment by stefanpejcic** [comment]
Yup, I've solved the problem in the same way.

**Comment by pingvi90** [comment]
**i solve my problem**:
in my way i set php version to 7.2 and "start php as FPM application ngix: https://prntscr.com/phdvgw

**Comment by ItsJustMyron** [comment]
Hey i'm now at version 3.1.1 and i'm getting this error and now my front page will not load theme: hestia

Uncaught ReferenceError: elementorModules is not defined
    at elementor-admin-bar.min.js?ver=3.1.1:2
    at elementor-admin-bar.min.js?ver=3.1.1:2
    at elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2
(anonymous) @ elementor-admin-bar.min.js?ver=3.1.1:2

**Comment by pocho5432** [comment]
@ItsJustMyron im having the same problem, did you solved it??

**Comment by ItsJustMyron** [comment]
> @ItsJustMyron im having the same problem, did you solved it??

Nope my host fixed the error but now i cant use Elemetor bcs if i open it my page is gone

**Comment by pocho5432** [comment]
@ItsJustMyron I knew that it has something to be with Autoptimizer. And I just found this and solved it...I hope it can help you:

"Untick the “also optimize for logged in editors/ administrators” near the bottom of Autoptimize’s main settings screen and all should work."

**Comment by shimonacarvalho** [comment]
@pocho5432 Thanks that worked for me.

**Comment by Akhilesh-Baboolull** [comment]
> @ItsJustMyron I knew that it has something to be with Autoptimizer. And I just found this and solved it...I hope it can help you:
> 
> "Untick the “also optimize for logged in editors/ administrators” near the bottom of Autoptimize’s main settings screen and all should work."

This worked for me.. Thanks @pocho5432

**Comment by jonathanarbely** [comment]
I had to completely deactivate the JS part in Autoptimizer for `ElementorModules` to work in Safari. I'll switch over to WPRocket soon, which is the recommended perf. plugin for Elementor anyways.

**Comment by nitria** [comment]
> @ItsJustMyron I knew that it has something to be with Autoptimizer. And I just found this and solved it...I hope it can help you:
> 
> "Untick the “also optimize for logged in editors/ administrators” near the bottom of Autoptimize’s main settings screen and all should work."

This helped me too!

**Comment by worksofman** [comment]
> @ItsJustMyron I knew that it has something to be with Autoptimizer. And I just found this and solved it...I hope it can help you:
> 
> "Untick the “also optimize for logged in editors/ administrators” near the bottom of Autoptimize’s main settings screen and all should work."

thank you for your comment. Helped me a lot

**Comment by Soullighter** [comment]
> Hi,
> 
> i had the problem as i was collaborating with a copywriter. He copied from the inside of elementors preview-window and pasted it into the text-field editor.
> 
> Nobody will see that there is elementor-raw-code in a text-field. By default the text-field is open with the [visual]-tab. Just open [text]-tab and search for elementor-html-code because that can cause elementor behaves with that error. At least thats how i fixed the problem.
> 
> kind regards andre

Same issue. I was Paste text and HTML tags with classes and ids brake my page. Sanitizing that HTML resolve my problem
