### ISSUE TITLE
Import of content (WXR-XML) works in admin, but not with WP-CLI

### ISSUE THREAD

**Issue by a-camacho** [pojome/elementor#4891]
===== Guidelines ====

First of all let me confirm that I've searched for an answer before, on Google and on this Github. We are also using last versions of Wordpress, Timber Plugin, Elementor Plugin.

I also checked that deactivating all plugins (except Elementor and Timber which our website needs and can't be deactivated) the problem persists. I also changed the theme to twenty-sixteen (and seventeen too) and the problem still exists.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

**Problem** : Trying to import a WXR-XML wordpress file from WP-Cli, the Elementor structure (sections and columns) breaks. Strangely, when I upload this file to Wordpress Importer the structure is not broken.

I attached two screenshots, one resulting for XML import from wp-admin (works), and one resulting from the import with WP CLI.

![working](https://user-images.githubusercontent.com/29976133/42025530-0fce35c2-7ac5-11e8-87c7-2aa43f12b307.png)
![not working](https://user-images.githubusercontent.com/29976133/42025531-0fe8a290-7ac5-11e8-857a-712b34a81fcc.png)
[wp-cli-log.txt](https://github.com/pojome/elementor/files/2144589/wp-cli-log.txt)

It seems that in XML file, page content is in two places : 
- <content:encoded> (text entered in wordpress editor ?)
- <![CDATA[_elementor_data]]> (content used by elementor)

It seems to me that when using WP CLI, it only gets content from the first tag. The elementor one seems to only be used when importing from wp-admin.

## Steps to reproduce

1. Use elementor on a website A
2. Export content (e.g: pages or everything) from wp-admin in a content.xml file
3. Import content.xml to website B (using same version of Wordpress and Elementor)
  a) using wp-cli (should not work and break structure)
  b) using importer from wp-admin (should work)

## Isolating the problem
- [-] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Server : Debian Stretch, PHP 7.1, Apache 2.4
Plugins : Elementor (+ Pro) and Timber Library on last version
Wordpress : Last stable version
```
</details>

Thank you very much for your help.
André Camacho

**Comment by bainternet** [comment]
@a-camacho 

Thanks for reporting, we will ship a fix in next version.

**Comment by HW-Siew** [comment]
Having the same issue. This is still not working in version 2.1.0-beta2?

**Comment by HW-Siew** [comment]
Hi guys, just tested it out in version 2.1.1, the fixed doesnt seem to be solving the issue at all. the same problem still when import content via WP-Cli.

**Comment by bainternet** [comment]
I merged this issue with  #4961, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by maheshwaghmare** [comment]
This is something strange that but the issue still exists.
Doing the same steps as provided by @a-camacho.
