### ISSUE TITLE
Elementor doesn't work 

### ISSUE THREAD

**Issue by juan-manuel-alberro** [pojome/elementor#52]
Hello,

I just installed Elementor and when I'm trying to edit a page with the builder I get this

![bug](http://storage2.static.itmages.com/i/16/0608/h_1465428590_6490410_f50c48741e.png)

The entire page is empty with just one button, any clue?

**Comment by yehudah** [comment]
Hello, 

If you refresh the page and press F12, what error message do you see in the console tab?

**Comment by KingYes** [comment]
@juan-manuel-alberro In current your WordPress, you have any cache plugin?

**Comment by juan-manuel-alberro** [comment]
@yehudah there's no errors in the console.
@KingYes latest version of Wordpress and I'm using WP Super Cache and then switch to W3C and they didn't work if the user is logged.
Please let me know if you need more information.

**Comment by KingYes** [comment]
@juan-manuel-alberro For the tests, can you disable all your Cache plugins?

**Comment by juan-manuel-alberro** [comment]
@KingYes here's without the cache plugin

![image](https://cloud.githubusercontent.com/assets/7114488/15929438/5f83c0fa-2e23-11e6-82c2-224d5c41c2ae.png)

No lucky and no errors in the console (it says that the session is over and I need to log in again, but I'm logged in)

**Comment by KingYes** [comment]
I just see this error before, and when we disable the Cache plugin, all work perfect.

I want to see the problem in my eyes, if you can, please send me Admin user for your website to our email: `support [at] elementor.com`. You can create new one for the tests..

**Comment by juan-manuel-alberro** [comment]
Sorry, I cant gave you access as admin into the site but maybe the list of plugins installed can help you to track the issue

```
AdSense Integration WP QUADS
Akismet
All In One SEO Pack
allfacebook Instant Articles
AMP
Better WordPress Minify
Contact Form 7
Disable Comments
Easy SwipeBox
Facebook Comments Plugin
G1 Socials
Gravitate Event Tracking
Jetpack por WordPress.com
MailChimp for WordPress
Mailgun
Mashshare Share Buttons
PACE Pro (EPIC Page Loading Progress Bar)
W3 Total Cache
WordPress Popular Posts
WP Editor
WP Smush
WP Subtitle
```

**Comment by juan-manuel-alberro** [comment]
I installed all those plugins and my theme in a dev env and the plugin is working, could it be related with the `https` protocol? Or the Nginx config?

**Comment by KingYes** [comment]
I think the problem is any Cache plugin. You need to try to deactivate and remove all extra config in `wp-config.php` + `wp-content/*cache*.php`.

**Comment by lukecav** [comment]
If you disable caching totally, does it work again?

**Comment by juan-manuel-alberro** [comment]
No, I removed the cache folder and disabled the plugin and no luck :(

**Comment by arielk** [comment]
Released a new version with fix for cache and minify plugins, please check it again.

**Comment by juan-manuel-alberro** [comment]
I just updated the plugin but doesn't work, I get the same error ... :(

**Comment by arielk** [comment]
If you deactivate all other plugins and then activate the TwentySixteen theme, the error is still there?

**Comment by juan-manuel-alberro** [comment]
@arielk still the same, could be related with some Nginx rule or with that server?

**Comment by arielk** [comment]
We released recently a new version (0.6 and up) please update your plugin and let me know if your bug has been resolved

**Comment by Olezka** [comment]
hello **arielk** I have same problem with empty screen. after new version any changes

**Comment by prakashgd** [comment]
![image](https://cloud.githubusercontent.com/assets/5779746/23100199/c7e14c6c-f6a0-11e6-85ee-2df622f97b27.png)

Even I get the same error page. Deactivated other visual editor plugin and cache plugin.

**Comment by arielk** [comment]
Is your entire website (backend & frontend) over HTTPS?

**Comment by prakashgd** [comment]
Yes

**Comment by WPDevHQ** [comment]
I've had this issue crop up a few times on an Nginx server but not on Apache.

I found reflushing the permalinks resolved the issue - if not already done so you might want to give that a go and see if it helps?

**Comment by terencechang** [comment]
Problem solved. I have **WP Super Cache** and **Elementor (Pro)** running. You just need to **uncheck** a box in the WP Super Cache setting. 

[[Solved] WordPress WP Super Page + Elementor = 404 Page Not Found](https://takeitoffroad.blogspot.com/2017/06/wp-super-cache-elementor-404.html)
