### ISSUE TITLE
Elementor Pro - 500 errors when saving with a global widget on page

### ISSUE THREAD

**Issue by ianlee** [pojome/elementor#5225]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
Attempting to save Global widgets throws a fatal error.

I believe this might be due to one of the newer updates to Elementor (non pro).
Encountered when Elementor (non pro) was updated today on a site.

Found these errors in my error log

[27-Jul-2018 01:16:45 UTC] PHP Notice:  Trying to get property of non-object in 
/public_html/wp-content/plugins/elementor-pro/modules/global-widget/module.php on line 127
[27-Jul-2018 01:16:45 UTC] PHP Fatal error:  Call to a member function render_plain_content() on null in /public_html/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php on line 125

## Steps to reproduce

Latest versions of Elementor and Elementor pro
create a page
place any widget (used text content)
turn widget into global widget
attempt to save.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.5.59
	PHP Version: 5.6.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: http://test.myloudspeaker.ca/~inmed/test
	Home URL: http://test.myloudspeaker.ca/~inmed/test
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.5
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.1.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.17
		Author: Elementor.com


== Debug ==
	Errors: There are no errors to display
				
```
</details>

**Comment by kaelmawn** [comment]
I have the same issue. I had to rollback to the previous version.

**Comment by chermaz** [comment]
Same issue for me...

**Comment by KingYes** [comment]
We released new patch to fix this. Thanks.

**Comment by obe1968** [comment]
@KingYes 

Where is the fix at please? I do not see it on Github, and my wordpress is still showing 2.1.5 from yesterday.

Thanks much!!!

**Comment by ianlee** [comment]
Thanks so much!  EPro 2.0.18 seems to have fixed the issue.

**Comment by Miguelangel777** [comment]
I experienced the same problem, but yesterday the elementor team solved it with the 2.0.18 update

**Comment by wpnovice** [comment]
I had the same issue - threw a 500 server error if a global button widget was on the page.  elementor pro 2.0.18 fixed it.  Thanks Elementor Team!
