### ISSUE TITLE
ACF date time picker Field support 

### ISSUE THREAD

**Issue by martinjakse** [pojome/elementor#6690]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Description
It would be great if Elementor (Pro) would support **ACF date time picker Field** out of the box, because it is easier to use instead of individual picker for date and time separately.

**Comment by shilo-ey** [comment]
Hi @martinjakse 

This has been fixed in Elementor Pro 2.4.4.

Feel free to update!

thanks.

**Comment by martinjakse** [comment]
Hi,

After upgrading to version EP 2.4.4 date time picker is still not visible - if I want to use it with "Title widget” or any other that support dynamic fields.  Can You give me some instructions on how to use ACF date time picker?

I would also like to know how to use “ACF color picker“ that is supported by Elementor ?

supported acf fields:
https://docs.elementor.com/article/381-elementor-integration-with-acf

Pro
‘oembed’, 
‘google_map’, 
‘date_picker’, 
‘time_picker’, 
‘color_picker’

**Comment by shilo-ey** [comment]
I just tested it again, it's working fine.

We will update the documentation.

regarding the color picker - it will retrieve the HEX of the color selected.

Thanks.

**Comment by zohar** [comment]
Using Elementor 2.4.7, Elementor Pro 2.4.5, ACF 5.7.12
Field of type date-time is not available under Elementor's Dynamic data drop down.

**Comment by ThomasDK81** [comment]
date_time_picker is not available under Elementor's Dynamic data drop down.
date_picker is.

**Comment by SNeilson** [comment]
I've also just tested this with the lastest version of both Elementor Pro and ACF @shilo-ey and no Date Time Picker field's are being displayed in the Dynamic Data dropdown.

**Comment by Rubenzella** [comment]
Elementor 2.9.8
Elementor Pro 2.9.3
Dynamic tags ACF data picker not displayed.
Are there any workarounds to make it works?

**Comment by Rubenzella** [comment]
> I've also just tested this with the lastest version of both Elementor Pro and ACF @shilo-ey and no Date Time Picker field's are being displayed in the Dynamic Data dropdown.

Make sure you select to preview the data from your ACFs.
